;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Item.State.Delivered",DevComment="")
+GameplayTagList=(Tag="Item.State.Painted",DevComment="")
+GameplayTagList=(Tag="Item.State.Produced",DevComment="")
+GameplayTagList=(Tag="Item.State.Raw",DevComment="")
+GameplayTagList=(Tag="Item.Type.Chair",DevComment="")
+GameplayTagList=(Tag="Item.Type.Chest",DevComment="")
+GameplayTagList=(Tag="Item.Type.Door",DevComment="")
+GameplayTagList=(Tag="Item.Type.Table",DevComment="")

